spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: abbas
    password:
    platform: h2
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
#      path: /h2-console
  output:
    ansi:
      enabled: always
assessment:
  mdsl:
    jwtSecret: MdslYItGHoldInGSecuritySecretKey
    jwtExpirationMs: 999999999